import { builtinModules } from 'module';
import { defineConfig, UserConfig } from 'vite';
import dts from 'vite-plugin-dts';

// https://vitejs.dev/config/
// vite config for building nebula lib modules
// dist dir is cleaned before build by vite
// types are generated by dts plugin
export default defineConfig((env) => {
  const viteBuildConfig: UserConfig = {
    build: {
      emptyOutDir: true,
      outDir: 'dist',
      sourcemap: true,
      lib: {
        entry: 'src/index.ts',
        formats: ['es', 'cjs'],
        fileName: 'index',
      },
      // TODO: Rollup warns about builins https://github.com/visgl/loaders.gl/issues/2000
      rollupOptions: {
        external: builtinModules,
      },
    },
    plugins: [
      dts({
        rollupTypes: true,
      }),
    ],
  };
  return viteBuildConfig;
});
