// @flow
export const MODES = {
  READ_ONLY: 'READ_ONLY',
  SELECT_FEATURE: 'SELECT_FEATURE',
  EDIT_VERTEX: 'EDIT_VERTEX',
  DRAW_POINT: 'DRAW_POINT',
  DRAW_PATH: 'DRAW_PATH',
  DRAW_POLYGON: 'DRAW_POLYGON',
  DRAW_RECTANGLE: 'DRAW_RECTANGLE'
};

export const DRAWING_MODES = [
  MODES.DRAW_POINT,
  MODES.DRAW_PATH,
  MODES.DRAW_POLYGON,
  MODES.DRAW_RECTANGLE
];

export const MODE_TO_GEOJSON_TYPE = {
  [MODES.DRAW_POINT]: 'Point',
  [MODES.DRAW_PATH]: 'LineString',
  [MODES.DRAW_POLYGON]: 'Polygon',
  [MODES.DRAW_RECTANGLE]: 'Polygon'
};

export const MODE_TO_RENDER_TYPE = {
  [MODES.DRAW_POINT]: 'Point',
  [MODES.DRAW_PATH]: 'LineString',
  [MODES.DRAW_POLYGON]: 'Polygon',
  [MODES.DRAW_RECTANGLE]: 'Rectangle'
};
