export const MODES = {
  READ_ONLY: 'READ_ONLY',
  SELECT: 'SELECT',
  EDITING: 'EDITING',
  DRAW_POINT: 'DRAW_POINT',
  DRAW_CIRCLE: 'DRAW_CIRCLE',
  DRAW_PATH: 'DRAW_PATH',
  DRAW_POLYGON: 'DRAW_POLYGON',
  DRAW_RECTANGLE: 'DRAW_RECTANGLE',
  DRAW_RECTANGLE_ONE_CLICK: 'DRAW_RECTANGLE_ONE_CLICK'
};
