export const MODES = {
  READ_ONLY: 'READ_ONLY',
  SELECT_FEATURE: 'SELECT_FEATURE',
  EDIT_VERTEX: 'EDIT_VERTEX',
  DRAW_POINT: 'DRAW_POINT',
  DRAW_PATH: 'DRAW_PATH',
  DRAW_POLYGON: 'DRAW_POLYGON'
};

export const DRAWING_MODES = [MODES.DRAW_POINT, MODES.DRAW_PATH, MODES.DRAW_POLYGON];

export const MODE_TO_GEOJSON_TYPE = {
  [MODES.DRAW_POINT]: 'Point',
  [MODES.DRAW_PATH]: 'LineString',
  [MODES.DRAW_POLYGON]: 'Polygon'
};
